### ISSUE TITLE
[Static] Clonenode overwrites

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-core#30]
- [x] recreate it in group test for example (needs attributes)
- [x] add static tests in group
- [x] fix it by using a field `nodeID: sid`-- if not make it and make new clone
- [x] also necessary for nested static elems that you remove/add

**Comment by nfrade** [comment]
Test case:

steps type:
```javascript
'use strict'

require('./style.css')

module.exports = {
  class: true,
  one: { text: 1 },
  two: { text: 2 },
  three: { text: 3 }
}
```

tpayStep2 modal:
```javascript
'use strict'

const steps = {
  type: 'steps',
  two: { class: 'active' }
}

(...)

```
https://github.com/vigour-io/play-modal/blob/master/lib/tpay/step2.js#L4

**Comment by jimdebeer** [comment]
as soon as a node is reused make a clone for the base version (a new one) this will avoid a lot of problems we are facing now

**Comment by jimdebeer** [comment]
need to add this no perf impact

**Comment by jimdebeer** [comment]
pretty important for slow internet (since it copies the src etc for images)
