### ISSUE TITLE
[req] I should have access to root element

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/brisky-core#33]
For me now root is `div` holder inside `body`.

To apply document related attributes, I need to have access to root element (`html` or sometimes `body`).

![image](https://cloud.githubusercontent.com/assets/962224/15799593/eea6048e-2a61-11e6-8512-8a73f19bfa46.png)

This reason is why. It works now but it's not nice :)

**Comment by julianshutt** [comment]
we can get the html element don't need it from brisky itself (this is jim btw)

**Comment by nikoloza** [comment]
I have to keep this issue open until I don't fix it.

**Comment by nikoloza** [comment]
This issue was moved to vigour-io/play-app#2
