### ISSUE TITLE
[bug] subscription acts like a bitch

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/brisky-core#34]
If we listen to direction right now (which is not a case i think), it does not subscribe well. 
https://github.com/vigour-io/play-modal/blob/fc311b2f4ed25d8461fcb0de16bdf031cdac6fc4/lib/types/row/index.js#L19

Also class is not a case.

I think it just does not update class when init and when change immediately. Only updates when you switch the page.

I have to use static icon for now (left arrow for rtl as well).

Short video: http://cl.ly/2i47383Q3Y1n

**Comment by nikoloza** [comment]
I also tried without `$transform` and `$prepend`, with `$test` and they just don't affect. Problem should be 100% in subscription

**Comment by jimdebeer** [comment]
think its fixed from state 4.0
